version: "3.8"

services:
    mongo:
        image: mongo
        container_name: my-mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        volumes:
            - ./db:/data/db
        ports:
            - "27017:27017" # 你也可以拔掉這行讓它只在網路內被看到
        networks:
            - dev-net

    nextjs:
        build:
            context: .
            dockerfile: Dockerfile
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
        container_name: next-prod
        environment:
            - MONGODB_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/confDb?authSource=admin
            - MONGODB_DB=confDb
            - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
            - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
            - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
            - NEXTAUTH_URL=${NEXTAUTH_URL}
            - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
            - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
            - EMAIL_USER=${EMAIL_USER}
            - EMAIL_APP_PASSWORD=${EMAIL_APP_PASSWORD}
            - EMAIL_SENDER_NAME=${EMAIL_SENDER_NAME}
            - ADMIN_EMAIL=${ADMIN_EMAIL}
            - ECPAY_MERCHANT_ID=${ECPAY_MERCHANT_ID}
            - ECPAY_HASH_KEY=${ECPAY_HASH_KEY}
            - ECPAY_HASH_IV=${ECPAY_HASH_IV}
            - ECPAY_QUERY_API_URL=${ECPAY_QUERY_API_URL}
            - ECPAY_API_URL=${ECPAY_API_URL}
        volumes:
            - ./uploads:/app/uploads # 保留 uploads 可寫入
        ports:
            - "3000:3000"
        depends_on:
            - mongo
        networks:
            - dev-net

    cloudflared:
        image: registry-1.docker.io/cloudflare/cloudflared:latest
        container_name: cloudflared
        command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
        networks:
            - dev-net
        depends_on:
            - nextjs
networks:
    dev-net:
        driver: bridge
